als=vim c:\cmder\config\aliases.cmd
gl=git log --oneline --all --graph --decorate  $*
gc=D: $t cd /github/ $t md $1 $t cd $1 $t git clone https://github.com/$1/$2 $t cd $2 $t vim .
..=cd ..
...=cd ../..
....=cd ../../..
.....=cd ../../../..
gs=git status
g=git
gcc=git commit -m $*
gaa=git add .
gd=git diff .
gp=git push
gu=git pull
gf=git fetch --all
gl=git log --oneline --all --graph --decorate $*
gka=git checkout .
gkb=git checkout -b $*
gk=git checkout $*
gb=git branch
gm=git merge $*
y=yarn $1
gc=D: $t cd D:\github\ $t md $1 $t cd $1 $t git clone https://github.com/$1/$2 $t cd $2 $t vim .
nge=D: $t cd D:\github\angular\angular-source\aio\content\examples $t code .
angular=D: $t cd D:\github\angular\angular-source $t code .
ngrx=D: $t cd D:\github\platform $t code .
