als=vim c:\cmder\config\aliases.cmd
gc=D: $t cd /github/ $t md $1 $t cd $1 $t git clone https://github.com/$1/$2 $t cd $2 $t vim .
..=cd ..
...=cd ../..
....=cd ../../..
.....=cd ../../../..
gs=git status
g=git
gcc=git commit -m $*
gaa=git add .
gd=git diff .
gp=git push
gu=git pull
gf=git fetch --all
gl=git log --oneline --all --graph --decorate $*
gka=git checkout .
gkb=git checkout -b $*
gk=git checkout $*
gb=git branch
y=yarn $1
nge=code D:\Projects\github\angular\aio\content\examples
angular=code D:\Projects\github\angular
ngrx=code D:\Projects\github\platform
